export enum QuizThemeKind {
    ANIMALS, BRAIN_TEASERS, CELEBRITIES, ENTERTAINMENT, GENERAL, GEOGRAPHY, HISTORY, HOBBIES, HUMANITIES, KIDS,
    LITERATURE, MOVIES, PEOPLE, RELIGION, SCIENCE, SPORTS, VIDEOGAMES
}